spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "032022"
  data:
    redis:
      host: localhost
      port: 6379
      password: "032022"
      database: 0


# Mybatis Mate ??
mybatis-mate:
  cert:
    grant: thisIsTestLicense
    license: as/bsBaSVrsA9FfjC/N77ruEt2/QZDrW+MHETNuEuZBra5mlaXZU+DE1ZvF8UjzlLCpH3TFVH3WPV+Ya7Ugiz1Rx4wSh/FK6Ug9lhos7rnsNaRB/+mR30aXqtlLt4dAmLAOCT56r9mikW+t1DDJY8TVhERWMjEipbqGO9oe1fqYCegCEX8tVCpToKr5J1g1V86mNsNnEGXujnLlEw9jBTrGxAyQroD7Ns1Dhwz1K4Y188mvmRQp9t7OYrpgsC7N9CXq1s1c2GtvfItHArkqHE4oDrhaPjpbMjFWLI5/XqZDtW3D+AVcH7pTcYZn6vzFfDZEmfDFV5fQlT3Rc+GENEg==

mybatis-plus:
  global-config:
    db-config:
      field-strategy: IGNORED
      column-underline: true
#      logic-delete-field: isDeleted # ????????????
#      logic-delete-value: 1 # ??????(??? 1)
#      logic-not-delete-value: 0 # ??????(??? 0)
      db-type: mysql
      id-type: assign_id
  mapper-locations: classpath*:/mapper/**Mapper.xml
#  type-aliases-package: com.zhifou.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
